#TODO change name
server:
  port: ${APP_SERVER_PORT:8080}
#  servlet:
#    context-path: /api

spring:
#  mvc:
#    servlet:
#      path: /api
  application:
    name: "@project.parent.artifactId@"
    version: "@project.version@"
  profiles:
    include:
      # TO enable specific-language documentations
      - swaggerEN
  zipkin:
    enabled: false
  sleuth:
    propagation:
      type: AWS

info:
  build:
    artifact: "@project.parent.artifactId@"
    name: "@project.parent.artifactId@"
    description: "@project.description@"
    version: "@project.version@"

logging:
  level:
    it.pagopa.pdv.person: ${APP_LOG_LEVEL:DEBUG}
