package it.pagopa.pdv.person.connector.dao.model;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import it.pagopa.pdv.person.connector.dao.PersonConnectorImpl;
import it.pagopa.pdv.person.connector.model.PersonDetailsOperations;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.FieldNameConstants;

import java.time.LocalDate;
import java.util.HashMap;
import java.util.Map;

@Data
@NoArgsConstructor
@FieldNameConstants(onlyExplicitlyIncluded = true)
@DynamoDBTable(tableName = PersonConnectorImpl.TABLE_NAME)
public class PersonDetails implements PersonDetailsOperations {

    public PersonDetails(String id) {
        this.id = id;
    }

    public PersonDetails(PersonDetailsOperations personDetails) {
        id = personDetails.getId();
        if (personDetails.getName() != null) {
            name = new DynamoCBCertifiableField<>(personDetails.getName());
        }
        if (personDetails.getFamilyName() != null) {
            familyName = new DynamoCBCertifiableField<>(personDetails.getFamilyName());
        }
        if (personDetails.getWorkContacts() != null) {
            workContacts = new HashMap<>(personDetails.getWorkContacts().size());
            personDetails.getWorkContacts().forEach((s, wc) -> workContacts.put(s, new WorkContact(wc)));
        }
    }

    @DynamoDBHashKey(attributeName = "PK")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBRangeKey(attributeName = "SK")
    public String getType() {
        return "Details";
    }

    public void setType(String type) {
        // intentionally left blank: SK is set by default
    }

    @DynamoDBAttribute
    private DynamoCBCertifiableField<String> name;

    @DynamoDBAttribute
    private DynamoCBCertifiableField<String> familyName;

    @DynamoDBAttribute
    private DynamoCBCertifiableField<String> email;

    @DynamoDBAttribute
    private DynamoCBCertifiableField<LocalDate> birthDate;


    @DynamoDBAttribute
    @FieldNameConstants.Include
    private Map<String, WorkContact> workContacts;


    @Data
    @NoArgsConstructor
    @DynamoDBDocument
    public static class WorkContact implements WorkContactOperations {

        public WorkContact(WorkContactOperations workContact) {
            if (workContact.getEmail() != null) {
                email = new DynamoCBCertifiableField<>(workContact.getEmail());
            }
        }

        @DynamoDBAttribute
        private DynamoCBCertifiableField<String> email;

    }

}
