package it.pagopa.pdv.person.connector.dao.model;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import it.pagopa.pdv.person.connector.dao.PersonConnectorImpl;
import it.pagopa.pdv.person.connector.dao.converter.LocalDateConverter;
import it.pagopa.pdv.person.connector.model.PersonDetailsOperations;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.FieldNameConstants;

import java.time.LocalDate;
import java.util.HashMap;
import java.util.Map;

@Data
@NoArgsConstructor
@FieldNameConstants(onlyExplicitlyIncluded = true)
@DynamoDBTable(tableName = PersonConnectorImpl.TABLE_NAME)
public class PersonDetails implements PersonDetailsOperations {

    public PersonDetails(String id) {
        this.id = id;
    }

    public PersonDetails(PersonDetailsOperations personDetails) {
        id = personDetails.getId();
        givenName = personDetails.getGivenName();
        familyName = personDetails.getFamilyName();
        if (personDetails.getWorkContacts() != null) {
            workContacts = new HashMap<>(personDetails.getWorkContacts().size());
            personDetails.getWorkContacts().forEach((s, wc) -> workContacts.put(s, new WorkContact(wc)));
        }
    }

    @DynamoDBHashKey(attributeName = "PK")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBRangeKey(attributeName = "SK")
    public String getType() {
        return "Details";
    }

    public void setType(String type) {
        // intentionally left blank: SK is set by default
    }

    @DynamoDBAttribute
    private String givenName;

    @DynamoDBAttribute
    private String familyName;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateConverter.class)
    private LocalDate birthDate;

    @DynamoDBAttribute
    @FieldNameConstants.Include
    private Map<String, WorkContact> workContacts;


    @Data
    @NoArgsConstructor
    @DynamoDBDocument
    public static class WorkContact implements WorkContactOperations {

        public WorkContact(WorkContactOperations workContact) {
            email = workContact.getEmail();
        }

        @DynamoDBAttribute
        private String email;

    }

}
