name: SonarCloud
on:
  push:
    branches:
      - main
      - release-*
    paths:
      - "**/src/**"
      - "**pom.xml"
      - ".github/workflows/code-review.yml"

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      AWS_REGION: eu-south-1
      AWS_ACCESS_KEY_ID: dummy-key
      AWS_SECRET_KEY: dummy-secrey-key
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - name: Set up JDK
      uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Prepare SonarCloud analysis configuration
      run: >
        mvn -Bclean org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report org.jacoco:jacoco-maven-plugin:report-aggregate
        -DpublishJUnitResults=true
        -DtestResultsFiles='**/surefire-reports/TEST-*.xml'
        -DjavaHomeOption='JDKVersion'
        -DmavenVersionOption='Default'
        -DmavenAuthenticateFeed=false
        -DeffectivePomSkip=false
        -DsonarQubeRunAnalysis=false
    - name: finding jacoco.xml
      run: |
        xmlReportPaths=$(find "$(pwd)" -path '*jacoco.xml' | sed 's/.*/&/' | tr '\n' ','); echo "##vso[task.setvariable variable=xmlReportPaths]$xmlReportPaths"

    - name: Analyze with SonarCloud
      run: > 
        mvn -B sonar:sonar
        -Dsonar.coverage.jacoco.xmlReportPaths=$xmlReportPaths
        -Dsonar.projectName=$SONARCLOUD_PROJECT_NAME
        -Dsonar.projectKey=$SONARCLOUD_PROJECT_KEY
        -Dsonar.organization=pagopa
        -Dsonar.host.url=https://sonarcloud.io 
        -Dsonar.login=$SONAR_TOKEN
        -Dsonar.exclusions='**/enums/**, **/model/**, **/*Constant*, **/*Config.java, **/*Scheduler.java, **/*Application.java, **/src/test/**, **/Dummy*.java'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONARCLOUD_PROJECT_KEY: ${{ vars.SONARCLOUD_PROJECT_KEY }}
        SONARCLOUD_PROJECT_NAME: ${{ vars.SONARCLOUD_PROJECT_NAME }}